apply plugin: 'com.android.application'

android {
    compileSdkVersion 19
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.yt.wrapper"
        minSdkVersion 19   // Android 4.4 KitKat
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}
